### ISSUE TITLE
NullPointerException - MCGoogleMap.init

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#188]
Заяц пожаловался.

java.lang.RuntimeException: Unable to start activity ComponentInfo{motocitizen.main/motocitizen.startup.Startup}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
at android.app.ActivityThread.access$600(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at motocitizen.maps.google.MCGoogleMap.init(MCGoogleMap.java:121)
at motocitizen.maps.google.MCGoogleMap.<init>(MCGoogleMap.java:45)
at motocitizen.startup.Startup.createMap(Startup.java:223)
at motocitizen.startup.Startup.onCreate(Startup.java:93)
at android.app.Activity.performCreate(Activity.java:5020)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)

Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=MCGoogleMap.java&tc=motocitizen.maps.google.MCGoogleMap&tm=init&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Надеюсь, что исправлено здесь: https://github.com/rjhdby/motocitizen/pull/189

**Comment by elagin** [comment]
Получилось.
