### ISSUE TITLE
NullPointerException - CreateAccActivity.onCreate

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#190]
Источник https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=CreateAccActivity.java&tc=motocitizen.Activity.CreateAccActivity&tm=onCreate&nid&an&c&s=new_status_desc

ava.lang.RuntimeException: Unable to start activity ComponentInfo{motocitizen.main/motocitizen.Activity.CreateAccActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
at android.app.ActivityThread.access$800(ActivityThread.java:138)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5111)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at motocitizen.Activity.CreateAccActivity.onCreate(CreateAccActivity.java:211)
at android.app.Activity.performCreate(Activity.java:5231)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
... 11 more

**Comment by elagin** [comment]
Ждем результатов.

**Comment by elagin** [comment]
Говорят что не воспроизводится.
