### ISSUE TITLE
NullPointerException - DetailVolunteersFragment.setupAccess

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#191]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=DetailVolunteersFragment.java&tc=motocitizen.Activity.DetailVolunteersFragment&tm=setupAccess&nid&an&c&s=new_status_desc

java.lang.RuntimeException: Unable to start activity ComponentInfo{motocitizen.main/motocitizen.Activity.AccidentDetailsActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
at android.app.ActivityThread.access$800(ActivityThread.java:138)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5111)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at motocitizen.Activity.DetailVolunteersFragment.setupAccess(DetailVolunteersFragment.java:155)
at motocitizen.Activity.DetailVolunteersFragment.update(DetailVolunteersFragment.java:125)
at motocitizen.Activity.DetailVolunteersFragment.onCreateView(DetailVolunteersFragment.java:87)
at android.app.Fragment.performCreateView(Fragment.java:1700)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1853)
at android.app.Activity.performCreate(Activity.java:5234)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)

**Comment by elagin** [comment]
Опять воспроизводится.

**Comment by elagin** [comment]
Судя по всем связано с https://github.com/rjhdby/motocitizen/issues/288 (попытка открыть не актуальный инцидент).

**Comment by rjhdby** [comment]
актуально?

**Comment by elagin** [comment]
Вероятно уже нет.
