### ISSUE TITLE
NullPointerException - AccidentDetailsFragments.update

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#193]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=AccidentDetailsFragments.java&tc=motocitizen.Activity.AccidentDetailsFragments&tm=update&nid&an&c&s=new_status_desc

***вылет при открытии из свернутых приложений***

java.lang.RuntimeException: Unable to start activity ComponentInfo{motocitizen.main/motocitizen.Activity.AccidentDetailsActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
at android.app.ActivityThread.access$600(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at motocitizen.Activity.AccidentDetailsFragments.update(AccidentDetailsFragments.java:20)
at motocitizen.Activity.DetailVolunteersFragment.update(DetailVolunteersFragment.java:124)
at motocitizen.Activity.DetailVolunteersFragment.onCreateView(DetailVolunteersFragment.java:87)
at android.app.Fragment.performCreateView(Fragment.java:1695)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
at android.app.BackStackRecord.run(BackStackRecord.java:694)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
at android.app.Activity.performStart(Activity.java:5131)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)

**Comment by elagin** [comment]
Выяснилась такая штука:
Запускаем приложение, открываем детали любого инцидента.
Срабатывает брекпоинт на DetailVolunteersFragment.onCreate и DetailVolunteersFragment.onCreateView

Сворачиваем приложение, находясь в описании.

Разворачиваем описание - видим список инцидентов. Выбираем ДРУГОЙ инцидент - переходим в стары, при этом onCreate и onCreateView не вызываются.

Жмем назад. В списке выбираем ЕЩЕ один другой инцидент и наблюдаем его.

Вывод: при сворачивании остается живым активити с подробностями, а попадаем мы почему-то в главный экран. Аналогичные проблемы попадались и в другом месте.

**Comment by rjhdby** [comment]
При старте приложение регистрирует свой базовый класс(Startup - он же main). При вызове из фона бросается интент именно в него.

**Comment by elagin** [comment]
Другие приложения так себя не ведут.

**Comment by rjhdby** [comment]
актуально?
