### ISSUE TITLE
Непонятный эксепш при приходе пуша

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#297]
05-25 14:29:33.010  16006-16374/motocitizen.main W/Bundle﹕ Key android.support.content.wakelockid expected String but value was a java.lang.Integer.  The default value <null> was returned.
05-25 14:29:33.030  16006-16374/motocitizen.main W/Bundle﹕ Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
            at android.os.Bundle.getString(Bundle.java:1061)
            at motocitizen.app.general.Accident.<init>(Accident.java:135)
            at motocitizen.app.general.gcm.NewAccidentReceived.onHandleIntent(NewAccidentReceived.java:50)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by rjhdby** [comment]
053a170e02a16af28e06efa4e8ed6cb7c43b82f0
