### ISSUE TITLE
Падение при работе без доступа к сети.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#312]
Если отключить сеть при запуске, то падает где-то в районе создания AuthActivity.
Если отключить сеть после запуска, то падает где-то еще.
Сильно не диагностировал, но подозреваю, что это из-за 
```
return new JSONObject();
```

**Comment by elagin** [comment]
05-27 18:34:36.267    2041-2073/motocitizen.main E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
     Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
            at android.os.Handler.<init>(Handler.java:197)
            at android.os.Handler.<init>(Handler.java:111)
            at android.widget.Toast$TN.<init>(Toast.java:350)
            at android.widget.Toast.<init>(Toast.java:95)
            at android.widget.Toast.makeText(Toast.java:242)
            at motocitizen.network.requests.HTTPClient.request(HTTPClient.java:49)
            at motocitizen.network.requests.HTTPClient.doInBackground(HTTPClient.java:44)
            at motocitizen.network.requests.HTTPClient.doInBackground(HTTPClient.java:33)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)

**Comment by elagin** [comment]
Нашел из-за чего возникает. Думаю, что в случае отсутствия сети возвращать не пустой объект, а что-то вроде {"error": "offline"}. Тогда при парсинге можно будет показать Toast юзеру. Этот же прием можно использовать для передачи других ошибок.
