### ISSUE TITLE
Не отображается адрес в верхней панели.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#392]
Осталась только кнопка "обновить" и "динамик".

**Comment by rjhdby** [comment]
Вот ваще не трогал

**Comment by rjhdby** [comment]
хотя...

**Comment by elagin** [comment]
Сейчас отображается. Как-то это странно.

**Comment by rjhdby** [comment]
```log
09-18 13:23:47.987      938-938/motocitizen.main W/System.err﹕ java.io.IOException: Service not Available
09-18 13:23:47.987      938-938/motocitizen.main W/System.err﹕ at android.location.Geocoder.getFromLocation(Geocoder.java:136)
09-18 13:23:47.987      938-938/motocitizen.main W/System.err﹕ at motocitizen.MyApp.getAddres(MyApp.java:55)
09-18 13:23:47.987      938-938/motocitizen.main W/System.err﹕ at motocitizen.geolocation.MyLocationManager.requestAddress(MyLocationManager.java:143)
09-18 13:23:47.987      938-938/motocitizen.main W/System.err﹕ at motocitizen.geolocation.MyLocationManager.access$200(MyLocationManager.java:21)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at motocitizen.geolocation.MyLocationManager$1.onLocationChanged(MyLocationManager.java:33)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at com.google.android.gms.internal.zzpe$zza.handleMessage(Unknown Source)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at android.os.Looper.loop(Looper.java:137)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:4794)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:511)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
09-18 13:23:47.997      938-938/motocitizen.main W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
09-18 13:23:48.007      938-938/motocitizen.main W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
09-18 13:23:53.497      938-940/motocitizen.main D/dalvikvm﹕ GC_CONCURRENT freed 728K, 12% free 15260K/17287K, paused 20ms+6ms, total 103ms
```

**Comment by elagin** [comment]
Больше не наблюдал.
