### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity 

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#420]
java.lang.RuntimeException: Unable to resume activity {motocitizen.main/motocitizen.activity.MainScreenActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void motocitizen.f.e.a(android.content.Context)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4158)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4252)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3363)
	at android.app.ActivityThread.access$1100(ActivityThread.java:223)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7231)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void motocitizen.f.e.a(android.content.Context)' on a null object reference
	at motocitizen.activity.MainScreenActivity.onResume(Unknown Source)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)
	at android.app.Activity.performResume(Activity.java:6988)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4147)
	... 10 more

**Comment by rjhdby** [comment]
#424
