### ISSUE TITLE
Вылет при старте

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#57]
3530-3530/motocitizen.main E/WindowManager﹕ Activity motocitizen.startup.Startup has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@423d0198 that was originally added here
    android.view.WindowLeaked: Activity motocitizen.startup.Startup has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView@423d0198 that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:374)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:292)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
            at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
            at android.view.Window$LocalWindowManager.addView(Window.java:547)
            at android.app.Dialog.show(Dialog.java:277)
            at motocitizen.network.HttpClient.onPreExecute(HttpClient.java:50)
            at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
            at android.os.AsyncTask.execute(AsyncTask.java:534)
            at motocitizen.startup.Startup.onResume(Startup.java:93)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
            at android.app.Activity.performResume(Activity.java:5082)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2573)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
            at android.app.ActivityThread.access$600(ActivityThread.java:133)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4794)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
            at dalvik.system.NativeStart.main(Native Method)

at motocitizen.startup.Startup.onResume(Startup.java:93)
            if (request != null) {
                (new IncidentRequest()).execute(request);
            }

**Comment by rjhdby** [comment]
Проблема с контекстом. Поправил в https://github.com/rjhdby/motocitizen/commit/af65cfcfe492985ae518d94da5ce9b499059bc4b

Ждем тестирования
